version: "3.9"

services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: dekakim_db
      POSTGRES_USER: dekakim_user
      POSTGRES_PASSWORD: your_secure_password

  backend:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    environment:
      - DEBUG=0
      - DJANGO_SUPERUSER_USERNAME=root
      - DJANGO_SUPERUSER_PASSWORD=root
      - DJANGO_SUPERUSER_EMAIL=root@example.com
      - ALLOWED_HOSTS=dekakim.net,www.dekakim.net
      - CSRF_TRUSTED_ORIGINS=https://dekakim.net https://www.dekakim.net
    expose:
      - 80

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  pgdata:
  static_volume:
  media_volume: