# Generated by Django 5.2.4 on 2025-07-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Block', 'verbose_name_plural': 'Blocks'},
        ),
        migrations.AlterModelOptions(
            name='blockphoto',
            options={'verbose_name': 'Block photo', 'verbose_name_plural': 'Block photos'},
        ),
        migrations.AlterModelOptions(
            name='blockvideo',
            options={'verbose_name': 'Block video', 'verbose_name_plural': 'Block videos'},
        ),
        migrations.AlterField(
            model_name='block',
            name='blocktype',
            field=models.CharField(choices=[('About us', 'About us'), ('Our vision', 'Our vision'), ('Our mission', 'Our mission'), ('Res. & Dev.', 'Res. & Dev')], max_length=20, verbose_name='Block type'),
        ),
        migrations.AlterField(
            model_name='block',
            name='language',
            field=models.CharField(choices=[('Eng', 'English'), ('Tur', 'Turkish')], default='Eng', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(max_length=1000000, unique=True, verbose_name='Post title'),
        ),
        migrations.AlterField(
            model_name='blockphoto',
            name='photo',
            field=models.ImageField(upload_to='blocks/photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='blockphoto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='about.block', verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='blockvideo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='about.block', verbose_name='Block'),
        ),
        migrations.AlterField(
            model_name='blockvideo',
            name='video',
            field=models.FileField(upload_to='blocks/videos/', verbose_name='Video'),
        ),
    ]
