# Generated by Django 5.2.4 on 2025-07-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='use',
            options={'verbose_name': 'Use case', 'verbose_name_plural': 'Use cases'},
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='TEMP-CODE', max_length=20, verbose_name='Product code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcode',
            field=models.CharField(default='TEMP-CODE', max_length=20, verbose_name='Product subcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='text',
            field=models.TextField(verbose_name='Feature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='face_img',
            field=models.ImageField(upload_to='cards/faces/', verbose_name='Main photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('Eng', 'English'), ('Tur', 'Turkish')], default='Eng', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slogan',
            field=models.TextField(verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='use',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='use',
            name='text',
            field=models.TextField(verbose_name='Use case description'),
        ),
    ]
