# Generated by Django 5.2.4 on 2025-07-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(default='Null', upload_to='categories/logos/', verbose_name='Category logo'),
            preserve_default=False,
        ),
    ]
