# Generated by Django 5.2.4 on 2025-07-15 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_description_category_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('Eng', 'English'), ('Tur', 'Turkish')], default='Eng', max_length=10, verbose_name='Language')),
                ('slogan', models.CharField(max_length=255, verbose_name='Slogan')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='banners/photos/', verbose_name='Photo')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
