# Generated by Django 5.2.4 on 2025-07-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
        ('products', '0003_alter_category_options_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyproduct',
            options={'verbose_name': 'Product purchase request', 'verbose_name_plural': 'Product purchase requests'},
        ),
        migrations.AlterModelOptions(
            name='employmentapplication',
            options={'verbose_name': 'Employment application', 'verbose_name_plural': 'Employment applications'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Example: +996707123456', max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_to_buy', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='employmentapplication',
            name='cv',
            field=models.FileField(upload_to='employees/cvs/', verbose_name='Resume (CV)'),
        ),
        migrations.AlterField(
            model_name='employmentapplication',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message or cover letter'),
        ),
        migrations.AlterField(
            model_name='employmentapplication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='employmentapplication',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Example: +996707123456', max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='employmentapplication',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
